### ISSUE TITLE
i ara què?

### ISSUE THREAD

**Issue by duub** [grautonomia/web#1]
després de compilar, crec que tot ha anat bé... el resultat del contingut són fitxers markdown, el pas per passar-los a html quin seria?

gràcies!

**Comment by doup** [comment]
Si has instalado las dependencias (npm y bower) y ejecutas `gulp build` te deberia de crear una carpeta `build` con todos los HTML/CSS/etc. That's it.

Lo único, todavia no he subido las imagenes/pdfs/etc. Que quiero hacer limpieza primero. De todas formas te deberia de funcionar (aunque no se vea como se tiene que ver).

**Comment by duub** [comment]
ah... ves quina cosa jo feia un "metalsmith -c build.js"

ara em surt aquest missatge:

```
[09:42:20] Using gulpfile ~/Development/grautonomia/gulpfile.js
[TypeError: Cannot read property 'apply' of undefined]
```

no se si tindrà res a veure amb que he deixat s3.json en blanc... però no crec, comentant aquesta línia segueix donant el mateix missatge:

```
gulp.task('deploy', gulp.series('build', 'upload'));
```

**Comment by doup** [comment]
`deploy` no tiene nada que ver. Solo se ejecuta si le das `gulp deploy`. Cuando haces `gulp` a secas se ejecuta el task `default`. Aunque ahora que lo veo, el README no esta actualizado… jeje, sorry. WIP ya tu sabes. ^_^U

Prueba:
1. `npm uninstall -g gulp`
2. `npm install -g gulpjs/gulp-cli#4.0`

Y si eso no te funciona, prueba de cero:
1. Borra `node` y el proyecto.
2. Instala la ultima versión de `io.js` (fork de Node.js)[1] con [nvm](https://github.com/creationix/nvm) (_on the bleeding edge_™)
3. `npm install -g gulpjs/gulp-cli#4.0 bower`
4. Bajate el proyecto, y en su carpeta haz:
   1. `npm install && bower install`
   2. `cp s3.json.txt s3.json`
   3. `gulp`

Los pasos 2 y 3 son los que no salen en el README.

1: Fork que en pocos meses parece que se volvera a integrar en Node.js

**Comment by duub** [comment]
al final ho he aconseguit començant de nou.
M'ha molat fer-me una mica a la idea de com va! Deu ni do quin festival de dependències!!
El resultat cosa fina :)
